name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Build and test with dotnet
      env:
        sentry-token: ${{ secrets.sentry_token }}
      run: |
        dotnet build src/SentryApi.Client.sln --configuration Release
        dotnet test src/SentryApi.Client.UnitTests/SentryApi.Client.UnitTests.csproj --configuration Release
        dotnet test src/SentryApi.Client.IntegrationTests/SentryApi.Client.IntegrationTests.csproj --configuration Release
