name: Publish

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Pack and publish with dotnet
      env:
        sentry-token: ${{ secrets.sentry_token }}
      run: |
        dotnet pack src/SentryApi.Client/SentryApi.Client.csproj --configuration Release
        dotnet nuget push **/*.nupkg -k ${{ secrets.nuget_api_key }} --source https://api.nuget.org/v3/index.json
